#!/bin/bash
#Check for Silent, or near silent WAV files.

if [ ! -f /usr/bin/sox ];
then
    echo "Please install sox" && exit 0
else
    echo "Sox Application Installed. Proceeding."
fi


MAX=0.0001

for wav in *.wav
	do
		V=$(sox "$wav" -n stat 2>&1 | grep "Maximum amplitude" | cut -d ":" -f 2 | sed 's/ //g')
		if [[ $(echo "if ("$V" > "$MAX") 1 else 0" | bc) -eq 0 ]]
#
# For testing, you can uncomment line 22, and comment line 23. This will REPORT the files to be deleted, without actually deleting them.
# Helpful if you need to tweak the value in line 8.
#
#			then echo "Would delete $wav";
			then rm -rfv $wav;
		fi
	done
