#!/bin/bash
#RW - 11.7.2022 - Running this one script should clean up all files in a given folder. Instead of having to run each part.

for WavFiles in ./000*.wav; do
   rm SE_LOG.BIN
   Split  $WavFiles
   rm 000*.wav
   Delete_Silent    
done
